#pragma once

#include "common/util/error.hpp"
#include "vulkan/container/device/attachment.hpp"
#include "vulkan/interface/attachment.hpp"
#include "vulkan/interface/context.hpp"

#include <expected>
#include <glm/ext/vector_uint2_sized.hpp>
#include <libassert/assert.hpp>
#include <utility>
#include <vulkan/vulkan.hpp>
#include <vulkan/vulkan_raii.hpp>

namespace render
{
	///
	/// @brief Shadow attachment
	///
	class ShadowAttachment
	{
	  public:

		static constexpr auto SHADOW_FORMAT = vk::Format::eR16G16Unorm;

		///
		/// @brief Create a shadow attachment
		///
		/// @param context Vulkan context
		/// @param command_buffer Command buffer for clearing images
		/// @param full_extent Full-resolution extent
		/// @return Created attachment or error
		///
		[[nodiscard]]
		static std::expected<ShadowAttachment, Error> create(
			const vulkan::Context& context,
			const vk::raii::CommandBuffer& command_buffer,
			glm::u32vec2 full_extent
		) noexcept;

		struct View
		{
			glm::u32vec2 half_extent;
			glm::u32vec2 full_extent;
			vulkan::AttachmentView init_sample;    // Initial samples generated by raytracer
			vulkan::AttachmentView denoise_imm;    // Immediate texture used by the denoiser
			vulkan::AttachmentView denoise_final;  // Final denoised result

			auto operator->() const noexcept { return this; }
		};

		operator View() const noexcept
		{
			return {
				.half_extent = half_extent,
				.full_extent = full_extent,
				.init_sample = init_sample,
				.denoise_imm = denoise_imm,
				.denoise_final = denoise_final,
			};
		}

		View operator->() const noexcept { return *this; }

	  private:

		glm::u32vec2 half_extent;
		glm::u32vec2 full_extent;
		vulkan::Attachment init_sample;
		vulkan::Attachment denoise_imm;
		vulkan::Attachment denoise_final;

		explicit ShadowAttachment(
			glm::u32vec2 half_extent,
			glm::u32vec2 full_extent,
			vulkan::Attachment init_sample,
			vulkan::Attachment denoise_imm,
			vulkan::Attachment denoise_final
		) :
			half_extent(half_extent),
			full_extent(full_extent),
			init_sample(std::move(init_sample)),
			denoise_imm(std::move(denoise_imm)),
			denoise_final(std::move(denoise_final))
		{}

	  public:

		ShadowAttachment(const ShadowAttachment&) = delete;
		ShadowAttachment(ShadowAttachment&&) = default;
		ShadowAttachment& operator=(const ShadowAttachment&) = delete;
		ShadowAttachment& operator=(ShadowAttachment&&) = default;
	};
}
